### ISSUE TITLE
tool availability

### ISSUE THREAD

**Issue by bmillerlab** [reinator/splace#1]
Hello,
I read your publication in Frontiers in Bioinformatics and was interested in actually trying this tool.  There does not seem to be an available tool to install at this time.  I am hoping you could tell me when the tool will actually be available to install and test?
Thank you.

**Comment by reinator** [comment]
Hi @bmillerlab .

Just download the file https://raw.githubusercontent.com/reinator/splace/main/splace.sh and follow the usage instructions on the github page.
